version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/" 
    schedule: 
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/ClientApp" 
    schedule: 
      interval: "daily"